# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safebox < Formula
  desc "A Fast and Flexible secret manager built with love by adikari in Go."
  homepage ""
  version "1.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monebag/safebox/releases/download/v1.3.8/safebox_1.3.8_darwin_arm64.tar.gz"
      sha256 "f27c92d4d2cdd8ab662f2d8d2931ad56f07d9cfe58ecad98b2dc74b3206d1ebd"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/monebag/safebox/releases/download/v1.3.8/safebox_1.3.8_darwin_amd64.tar.gz"
      sha256 "5460b1df50112890816d43c9795ec4d2680058907e921015833dd160e9de90fd"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/monebag/safebox/releases/download/v1.3.8/safebox_1.3.8_linux_amd64.tar.gz"
      sha256 "c019538a55905fe603d0f57913398dec4dcde32af7c9eeca83be1f52d2b8c1ef"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monebag/safebox/releases/download/v1.3.8/safebox_1.3.8_linux_arm64.tar.gz"
      sha256 "c6bdbddbd3c5c1d1d7a6a597a043ba97328e7fa3ed891d408af70d94b2319c46"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  test do
    system "#{bin}/safebox --version"
  end
end
