# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safebox < Formula
  desc "A Fast and Flexible secret manager built with love by adikari in Go."
  homepage ""
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adikari/safebox/releases/download/v1.1.3/safebox_1.1.3_darwin_amd64.tar.gz"
      sha256 "44413b2978e4d80d017ecb6405f7f7b7e0106a0c849d615f7aa6cf1b2e55b9e2"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adikari/safebox/releases/download/v1.1.3/safebox_1.1.3_darwin_arm64.tar.gz"
      sha256 "9b9b646ea84709a68d7ec83723b9fe9234a9de532916f19d9c72f77fef5bdf38"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/adikari/safebox/releases/download/v1.1.3/safebox_1.1.3_linux_amd64.tar.gz"
      sha256 "7aacc903ed25d567907a7c2040295cfb852e815e29a2408d863b39a582a12748"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adikari/safebox/releases/download/v1.1.3/safebox_1.1.3_linux_arm64.tar.gz"
      sha256 "658dc13257d38096cfd7d611a28ea6b79a792313aebca3f80741b66b38844bbf"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  test do
    system "#{bin}/safebox --version"
  end
end
