# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safebox < Formula
  desc "A Fast and Flexible secret manager built with love by adikari in Go."
  homepage ""
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monebag/safebox/releases/download/v1.3.0/safebox_1.3.0_darwin_amd64"
      sha256 "c39dbef69970d762b819daade939ca678fabd88f4151a3e352d61b528c2eca4d"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monebag/safebox/releases/download/v1.3.0/safebox_1.3.0_darwin_arm64"
      sha256 "b5ec19f94f2c59b25ff7c0ce4b0c6933e97f1d44e3bf4496b0f780f654b3055a"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/monebag/safebox/releases/download/v1.3.0/safebox_1.3.0_linux_amd64"
      sha256 "7f3abdacf3c479e2405012e07cfa04913bb00f8af79bdef87539d4344a1851b4"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monebag/safebox/releases/download/v1.3.0/safebox_1.3.0_linux_arm64"
      sha256 "f2d628dbdd8cc4579d9538e79a58ed85bf62fa7f00e95cdb561988a4fd0084a0"

      def install
        bin.install "safebox"
        bash_completion.install "completions/safebox.bash" => "safebox"
        zsh_completion.install "completions/safebox.zsh" => "_safebox"
        fish_completion.install "completions/safebox.fish"
      end
    end
  end

  test do
    system "#{bin}/safebox --version"
  end
end
